services:
  app:
    build:
      context: ./
    depends_on:
      - db-feb
    restart: always
    environment:
      token_discord: ${token_discord}
      token_uptime: ${token_uptime}
      token_botsondiscord: ${token_botsondiscord}
      token_discordbotlist: ${token_discordbotlist}
      token_discords: ${token_discords}
      token_discordbots: ${token_discordbots}
      token_motiondevelopment: ${token_motiondevelopment}
      token_saucenao: ${token_saucenao}
      login_fa_cookie_a: ${login_fa_cookie_a}
      login_fa_cookie_b: ${login_fa_cookie_b}
      login_e621_user: ${login_e621_user}
      token_e621: ${token_e621}
      db_dialect: mysql
      db_host: db-feb
      db_name: furExplicitBot
      db_user: furExplicitBot
      db_passw: ${db_password}
      sentryLink: ${SENTRY_LINK}
    logging:
      driver: "json-file"
      options:
        max-size: "1G"

  worker_faautpost:
    build:
      context: .
      dockerfile: ./workers/faAutopost/Dockerfile
    depends_on:
      - db-feb
    restart: always
    environment:
      token_uptime_worker: ${token_uptime_worker}
      login_fa_cookie_a: ${login_fa_cookie_a}
      login_fa_cookie_b: ${login_fa_cookie_b}
      db_dialect: mysql
      db_host: db-feb
      db_name: furExplicitBot
      db_user: furExplicitBot
      db_passw: ${db_password}
      sentryLink: ${SENTRY_LINK}
    logging:
      driver: "json-file"
      options:
        max-size: "1G"

  db-feb:
    image: mariadb:latest
    restart: always
    ports:
      - "${db_ip}:${db_port}:3306"
    volumes:
      - db_data:/var/lib/mysql
    # Set max_allowed_packet https://stackoverflow.com/questions/39369367/increase-max-allowed-packet-size-in-mysql-docker
    command: --max_allowed_packet=256M
    environment:
      MYSQL_ROOT_PASSWORD: ${db_password_root}
      MYSQL_DATABASE: furExplicitBot
      MYSQL_USER: furExplicitBot
      MYSQL_PASSWORD: ${db_password}
    logging:
      driver: "json-file"
      options:
        max-size: "1G"
    networks:
      - default
      - grafana_exposed

  redis:
    image: eqalpha/keydb:alpine_x86_64_v6.3.4
    command: keydb-server /etc/keydb/redis.conf --server-threads 2
    volumes:
    #  - ./keydb.conf:/etc/keydb/keydb.conf
      - redis_data:/data
    restart: always

networks:
  grafana_exposed:
    external: true

volumes:
  db_data:
  redis_data:

